### ISSUE TITLE
QR Code invalid after adding booster to app

### ISSUE THREAD

**Issue by sourcloud** [Digitaler-Impfnachweis/covpass-ios#78] opened 2021-12-06 20:08 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11
- OS version: 15.1
- App version: 1.13 (5)

## Describe the bug

After I received my booster vaccination and stored it in the CovPass app as vaccination (3/3), the QR code was displayed as invalid when scanned with the CovPass Check app - even after multiple scans.

The problem could be solved by displaying and scanning the QR code of the second vaccination (2/2). After that, the QR code of the third vaccination was also displayed as valid when scanned again.

## Steps to reproduce the issue

- Receive booster vaccination
- Store booster vaccination in CovPass app (3/3)
- Scan QR code of (3/3) - should display as invalid
- Scan QR code of (2/2) - should display as valid
- Scan QR code of (3/3) again - should now display as valid

## Expected behaviour

The QR code for the booster vaccination (3/3) should be valid on the first scan without having to scan the older QR code first.

## Additional context

The problem occurred on two different iPhones with the same OS and app version scanning each other. I don't know if it's the CovPass or the CovPass Check app and if Android devices are also affected.

**Comment by jleufgen** [comment] 2021-12-07 14:38
@sourcloud thanks for the hint! Is this bug still reproducible for you? We couldn't reproduce it with the latest app version.

**Comment by alexcimander** [comment] 2021-12-07 14:42
Hey Sourcloud,

additional to @jleufgen - some information that might help us to reproduce the issue:
- Is the used ruleset up-to-date?
- Which country are you checking?
- Which point in time are you checking against?

Thank you :-)

**Comment by papascott** [comment] 2021-12-08 10:34
I've just seen this same behavior. Rule set up-to-date (10 minutes old), country is Germany, cert 3/3 dated 08 Dec 21, cert 2/2 dated 08 Jul 21.

**Comment by JohannLange** [comment] 2021-12-08 12:59
After manually updating the ruleset in the settings, the booster certificate is shown as valid for me.
Earlier today it wasn't.

**Comment by timokoenig** [comment] 2021-12-14 12:50
Maybe @jleufgen has more information on that

**Comment by alexcimander** [comment] 2021-12-15 13:16
hey everyone, we are currently investigating on the behavior - we will provide an update as soon as possible, thank you for reporting and discussing the issue! 🚧

**Comment by Khesp** [comment] 2021-12-22 20:19
Maybe as a help to reproduce. When I uninstall and reinstall the CovPass Check app and then scan the QR code of a third vaccination, it shows it as invalid. If I scan the QR code again, it will always be shown as a valid certificate from now on.  If I uninstall the app and install it again, the first time I scan the certificate of the third vaccination, it shows it as invalid again.

**Comment by timokoenig** [comment] 2021-12-22 21:07
The behavior @Khesp describes is very logical. The app ships with a static list of rules (this initial list gets updated when the app is being published to the App Store) After the app gets installed the rules will be updated every 24 hours. It seems that the initial ruleset contains a rule that would decline the certificate and in the current ruleset this rule got deleted.

Also note that the first update might take a little longer depending on the difference of the initial ruleset and the current ruleset. That might be the reason why you need to scan it multiple times before you see a different result.

**Comment by timokoenig** [comment] 2021-12-22 21:12
The rule that got updated is **VR-DE-0003** which is `At least 14 days must have elapsed since completing the primary course of immunization. A booster shot or vaccination of someone who recovered from COVID-19 is valid immediately as long as it is clearly identified as such.`

https://distribution.dcc-rules.de/rules/DE/f19e4792aeaffc8aba2ad59a851cbd3ceea6c0f44cafdb31cbeea6a6dcc7610e

This rule checks for the 14 day period but allows boosters to be valid immediately. We need to keep in mind that some boosters can not be detected properly due to the EU decisions on how to create booster certificates.

This rule is not included in the Check app that is currently in the App Store but it will be updated after you open the app and connect it to the internet. You should be able to see the date when the ruleset got updated on the overview screen.

**Comment by Khesp** [comment] 2021-12-22 21:31
I think I have now found why the message, that the certificate is not valid, is shown after reinstallation in my case. I noticed that after starting the app, the list for the certificate issuer is updated. However, I must wait until the message appears (at the bottom of the app) that the rule set has been updated. After that I can scan the third vaccination without any problems. I didn't think about it at first, because the second vaccination also works after the reinstallation, before the rule set is updated.

**Comment by Ein-Tim** [comment] 2021-12-22 21:36
@timokoenig 

Wouldn't it make sense to update the list included in the app store package then?

**Comment by Khesp** [comment] 2021-12-22 21:38
> The behavior @Khesp describes is very logical. The app ships with a static list of rules (this initial list gets updated when the app is being published to the App Store) After the app gets installed the rules will be updated every 24 hours. It seems that the initial ruleset contains a rule that would decline the certificate and in the current ruleset this rule got deleted.
> 
> Also note that the first update might take a little longer depending on the difference of the initial ruleset and the current ruleset. That might be the reason why you need to scan it multiple times before you see a different result.

Now I read your comment too late @timokoenig. Think it's exactly as you describe.

**Comment by timokoenig** [comment] 2021-12-22 21:39
@Ein-Tim this should be the case every time a new app version gets published on the App Store. There already must be a version in the pipeline since the last CheckApp is four weeks old

**Comment by alexcimander** [comment] 2021-12-23 08:35
Hi everyone,

we investigated the problem and yes - @timokoenig got it right. The local ruleset seems to be outdated which causes the issue after installation, since the update of the rules can take some time the outdated rules are still taking effect for the first checks. For now we encourage you to **manually update the rules after the installation using the "manual update" functionality within the settings**. The update can take some seconds.

We will fix the issue asap (latest with 1.16) and will work on the overall rule update performance - we will keep you updated. 

Thank you everyone! 👍

**Comment by Kurt57** [comment] 2022-03-22 14:48
@sourcloud is this problem still present or can we close this ticket?

**Comment by timokoenig** [comment] 2022-10-26 13:31
Every new app ships with an updated list of rules and DSCs that update shortly after the app opens. Since the original post author possibly had an outdated list, I will consider this as resolved.

**Closed by timokoenig** 2022-10-26 13:31 UTC
Labels: bug
