### ISSUE TITLE
App only shows a white screen

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#20] opened 2021-06-25 21:54 UTC
## Technical details

- Device name: iPhone SE 1. Gen
- iOS version: 12.1
- App version: 1.3.0

## Describe the bug

After scanning the vaccination QR-Code, which was downloaded from the [Bavarian Impfportal](https://impfzentren.bayern/citizen/), and clicking on "Aktuellen QR-Code anzeigen" the QR-Code is not shown but the app only shows the start screen which is completely white:

<img src="https://user-images.githubusercontent.com/67682506/123487733-d10b5880-d60e-11eb-8ee1-daf3f84d9fc9.jpeg" width="300">

## Steps to reproduce the issue

1. Scan a vaccination QR-Code
2. Click on "Aktuellen QR-Code anzeigen"
3. See that the app shows a completely white screen, as shown in the screenshot above

## Expected behaviour

The home screen shouldn't be completely white but show the QR-Code. 

## Additional context
1. This is most likely an iOS 12(.1) exclusive bug since I'm not able to reproduce this under iOS 14.6. 
2. Reinstall of the app did not help - same problem occurred again
3. Clicking on the + icon and scanning the same certificate again leads to the error message "COVID-Zertifikat wurde bereits hinzugefügt"

**Comment by christophfriedrich** [comment] 2021-06-26 13:59
I'm experiencing *exactly* this error too! So this can be considered reproduced (on an iPhone 6s with iOS 12.1.2 and app version 1.3.0). Even the rescanning error is the same. I thought about reinstalling, but after reading the issue above I didn't bother. Would be great to get this fixed!

**Comment by timokoenig** [comment] 2021-06-28 13:03
I haven't seen this behavior yet but I will look into this

**Comment by christophfriedrich** [comment] 2021-06-28 15:23
Nice! :+1: Let me know if you need any further information or someone to test a possible fix (I don't have a Mac though to install something via Xcode or the likes)

**Comment by timokoenig** [comment] 2021-06-30 18:17
Bug is confirmed. I'm working on a fix

**Note**: The data is not lost, it's just an UI display issue

**Comment by tb-tw** [comment] 2021-07-03 07:45
On Android version 11, I also get to see only a white screen. So the bug might be independent of the operating system...

**Comment by Ein-Tim** [comment] 2021-07-03 08:20
@tb-tw 

Thanks for the information. Since I think it's quite unlikely that the issue on your Android device has the same root cause as the issue under iOS, I'd like to ask you to [open a new issue in the Android repository](https://github.com/Digitaler-Impfnachweis/covpass-android/issues/new).

Thank you!

**Comment by tb-tw** [comment] 2021-07-03 08:36
Done!On 03/07/2021, 10:20 Tim ***@***.***> wrote:

   
  @tb-tw 
  Thanks for the information. Since I think it's quite unlikely that the issue on your Android device has the same root cause as the issue under iOS, I'd like to ask you to open a new issue in the Android repository. 
  Thank you!

**Comment by timokoenig** [comment] 2021-07-13 19:40
The white screen bug has been fixed with version 1.4.1

**Closed by timokoenig** 2021-07-13 19:40 UTC
Labels: bug
