### ISSUE TITLE
Unable to renew certificate within 1.26

### ISSUE THREAD

**Issue by burnziii** [Digitaler-Impfnachweis/covpass-ios#194] opened 2022-06-08 16:00 UTC
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 13 Pro
- OS version: iOS 16.0 (20A5283p)
- App version: 1.26

## Describe the bug

When checking my certificate 1/3 it is shown that it will expire soon and that it can be renewed within the certificate overview, but there is no button for it anywhere.

## Steps to reproduce the issue

1. Go to "show certificate"
2. Click on "manage certificates"
3. Scroll down to certificate 1
4. Click on the first certificate which shows "expiring soon (less than 10 days)"
5. It is shown that this certificate will expire soon and it can be renewed from the certificate overview.
6. At the overview there is no option to renew the certificate
-->

## Expected behaviour

A button to renew the certififacte within the overview or at the detail page of the expiring certififacte.

## Possible Fix

?

**Comment by timokoenig** [comment] 2022-06-08 16:04
@burnziii we just had a similar discussion in the Android repository. The button will only appear for your last certificate that is about to expire. The UI is not very clear for this feature

**Comment by burnziii** [comment] 2022-06-08 16:05
So I only have the option to renewe the certificate if the last valid one expired?

**Comment by timokoenig** [comment] 2022-06-08 16:09
In general you don't really need the other certificates to renew. In case of travel or other entry checks the latest full vaccination / booster certificate is enough.

I heard about a workaround that seems to work for Android where you delete the newer certificates and with only the expiring certificate you should be able to renew it, but I couldn't confirm it.

**Comment by Ein-Tim** [comment] 2022-06-08 16:11
@burnziii Could you maybe share a screenshot with us how the screen where it says your certificate is (about to) expire(d) looks? Black out QR-Code and other personal details, please!

---

On topic, I suggest you take a look at [CWA 2.23: Extension of technically expired certificates in the CWA](https://www.coronawarn.app/en/blog/2022-06-01-cwa-2-23/) which says:

"**Recovery certificates** can always be renewed when they are about to expire technically. For **vaccination certificates**, users only need to renew the certificate currently in use, as it contains sufficient information about vaccination protection. For users who have stored three vaccination certificates in the CWA, this means that the vaccination certificate of the first and second vaccination will not be exchanged, but only the vaccination certificate of the booster vaccination as soon as it is about to expire."

**Comment by burnziii** [comment] 2022-06-08 16:21
Here are the screens from the overview and the detail of the certificate.

![image](https://user-images.githubusercontent.com/16451502/172667405-08c824c9-087c-44df-9738-ebd752d70792.jpeg)
![image](https://user-images.githubusercontent.com/16451502/172667428-3213fddc-a768-4a31-a21e-6cdd5ee81f09.png)

**Comment by timokoenig** [comment] 2022-06-08 16:23
Similar to my certificates. I can confirm this behavior

**Comment by Ein-Tim** [comment] 2022-06-08 16:24
Okay, thanks! So the problem really is that the note that the certificate expires soon does not include any hint that the renewal function is not available for certificates which are not currently used. This is really really bad UI. CWAs text at least says that if the certificate is not the currently used certificate, there is nothing you need to do. CovPass is really bad here.

This should be fixed with a hot fix IMO. Thanks @timokoenig for confirming!

**Comment by burnziii** [comment] 2022-06-08 16:28
If this soon expiring certificate is not needed to be renewed then there should be a check within the app that checks if there are other newer certificates which lead to no need to renew this certificate. Something like "Zertifikat läuft bald ab, erneuerung nicht notwendig" would maybe help or a message in the detail view that it will expire but renew is not needed would help.

I think right now it is confusing and the release notes will make people think that they can renew all of their certificates.

Otherwise why not renew all expired certificates if it is technically possible?

**Comment by Ein-Tim** [comment] 2022-06-08 16:32
> If this soon expiring certificate is not needed to be renewed then there should be a check within the app that checks if there are other newer certificates which lead to no need to renew this certificate. Something like "Zertifikat läuft bald ab, erneuerung nicht notwendig" would maybe help or a message in the detail view that it will expire but renew is not needed would help.

100% agreed. The UI needs improvement.

> Otherwise why not renew all expired certificates if it is technically possible?

Because it is not necessary. In your case for example the 3/3 certificate holds all information.

**Comment by alexcimander** [comment] 2022-06-09 10:58
Hey everyone! Update: We are currently working on a HF 1.26.1 which will take care of:

**1.) Wrong reason for Re-Issue mentioned (Android only)**
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/211
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/210

**2.) Misleading Text for (about to be expired) DCCs in DCC-Details**
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/212
https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/194

**3.) Misleading Text within renewal process**
https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/192

**4.) "there are news" but not "there is news" within notification**
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/217  

**5.) In Investigation: "No renewal offered for 1/2 vaccination if it is the only vaccination**  

-------------------------------------------------------

the bugs 

6.) Notification about expiry is played out twice (Android only)
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/214

7.) Re-Open of the App required (Android only) is not stated by the info text
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/213

are currently in investigation - we will provide a fix asap but these two are not expected to be fixed within the HF.


Thank you all for the patience and supporting discussions! 🦸

**Comment by mirabilos** [comment] 2022-06-13 03:44
The workaround to temporarily remove the 3/3 cert to renew the 1/2 and 2/2 ones works-ish: the button does show up, *both* certificates are listed to be transmitted… and only the 2/2 cert is renewed, not the 1/2 one.

Einmal mit Profis arbeiten…

**Comment by Ein-Tim** [comment] 2022-06-13 04:16
@mirabilos 

Why would you like to renew the 1/2 certificate? Is it not valid anyways.

**Comment by Ein-Tim** [comment] 2022-06-14 18:38
@burnziii 


Could you re-check if the UI has improved with version 1.26.1?

**Comment by burnziii** [comment] 2022-06-14 18:38
Yes, big improvement..

**Comment by Ein-Tim** [comment] 2022-06-14 18:45
@burnziii 

Okay, so if you consider this as fixed, please close the issue. (:

**Comment by timokoenig** [comment] 2022-06-14 18:46
Text still indicates that the certificate can be renewed but it can't because there are newer certificates. I would suggest to leave this open

**Comment by timokoenig** [comment] 2022-06-14 19:54
I somehow had an old app state. Everything is fine now.

**Comment by mirabilos** [comment] 2022-10-11 09:23
Tim dixit:

***@***.*** 
>
>Why would you like to renew the 1/2 certificate? Is it not valid anyways. 

To get rid of warning messages, of course. And it certainly is valid,
I hope, just not sufficient for current checks.

**Closed** 2022-12-02 20:35 UTC
Labels: bug
