### ISSUE TITLE
App freeze while adding 2nd certificate

### ISSUE THREAD

**Issue by weinzierl-florian** [Digitaler-Impfnachweis/covpass-ios#127] opened 2022-02-06 21:33 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 13 Pro
- OS version: 15.2.1
- App version: 1.17

## Describe the bug

First vaccination happened using a single dose of J&J. Now had a second dose of BioNTech.
I got told, to wait at least 14 days before I scan my 2nd QR-Code or the app will remove all certificates and I did so.
But as I tried to scan my 2nd QR-Code today, the app always freezes. Closing the app and reopening it only shows the first certificate scanned last year. Even deleting and reinstalling the app did not change anything at all. (I added the certificates in the same order as they were issued.) 

## Steps to reproduce the issue
 ¯\\_(ツ)_/¯ Everything I did is described above...

## Expected behaviour
I expected the second QR-Code will be added as if it was "a regular" second dose (Maybe this happens because the first one was J&J?)

**Comment by Ein-Tim** [comment] 2022-02-06 21:34
Is the certificate a 2/2 certificate ("Impfung 2 von 2") or a 2/1 certificate ("Impfung 2 von 1")?

**Comment by weinzierl-florian** [comment] 2022-02-06 21:37
It says 2/2 on the EU-printout i got.

**Comment by timokoenig** [comment] 2022-02-07 00:26
> I got told, to wait at least 14 days before I scan my 2nd QR-Code or the app will remove all certificates

That is not the reason why some people had to wait 14 days. In your case with BioNTech 2/2 you are considered fully vaccinated after 14 days. That's why its better to wait because the rules sometimes can't distinguish between full vaccination and booster.

Anyways, no matter what kind of certificate it is, the app should not freeze. I would guess that the recent changes with 2G+ had something to do with it. @Kurt57 is this a known issue?

**Comment by alexcimander** [comment] 2022-02-08 07:38
Hey everyone,

we are investigating the issue. For now it was not reproducible. @weinzierl-florian do you know with what version of the app you did your first scan? (or at least a rough timeframe?).

**Comment by weinzierl-florian** [comment] 2022-02-08 11:01
> > I got told, to wait at least 14 days before I scan my 2nd QR-Code or the app will remove all certificates
> 
> That is not the reason why some people had to wait 14 days. In your case with BioNTech 2/2 you are considered fully vaccinated after 14 days. That's why its better to wait because the rules sometimes can't distinguish between full vaccination and booster.
 
I can only repeat, what I was told while getting the vaccination... But as you pointed out, i don't think this has anything to do with the error I'm facing.



> Hey everyone,
> 
> we are investigating the issue. For now it was not reproducible. @weinzierl-florian do you know with what version of the app you did your first scan? (or at least a rough timeframe?).

The first ever scan was around 28.08.2021. I can't quite remember whether I scanned it that day, or waited 14 days. But that's the rough timeframe.

But as I mentioned above, I completely removed the application from my iPhone, reinstalled it from the App Store and scanned the first EU-printout again, which worked like a charm, but as soon as I'm trying to scan the 2nd one, the App still freezes.

**Comment by RedStylzZ** [comment] 2022-02-20 16:05
I scanned my Dose of BioNTech (first was J&J) on 28.11.21 and it worked fine. Today I wanted to scan my second BioNTech and it freezes every time and only Shows the last to certificates.

**Comment by timokoenig** [comment] 2022-02-20 18:19
@RedStylzZ can you confirm that your iPhone has enough free space?

**Comment by RedStylzZ** [comment] 2022-02-20 18:39
> @RedStylzZ can you confirm that your iPhone has enough free space?

Yes

**Comment by timokoenig** [comment] 2022-02-20 18:42
@RedStylzZ thanks, that's weird. I would have a look but I'm waiting for https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/137

**Comment by timokoenig** [comment] 2022-02-28 17:08
I might have found a possible reason why the app freezes. The compression algorithm of this app has an endless loop because of an supposedly Apple bug (mentioned in the code): https://github.com/Digitaler-Impfnachweis/covpass-ios/blob/f774e681baf0a737661dce6ad393cc82b69f33ee/Source/CovPassCommon/Sources/CovPassCommon/Compression/Compression.swift#L48

The team should look into this issue, either fix it or use a compression library that works fine.

**Comment by alexcimander** [comment] 2022-03-08 13:36
Thank you Timo for your investigation - we created a ticket for it and we will keep you all updated about it

**Comment by timokoenig** [comment] 2022-03-13 17:19
@alexcimander I would suggest to set the priority of this ticket to highest and publish a hotfix asap. Just have a look at the App Store reviews. This is a major problem.

I stick with my idea that this is has something to do with the decompression. It occurs only with newer certificates and this would mean that the compression algorithm changed in the backend that creates the certificates. Maybe Ubirch can help you out to find the cause of this problem.

**Comment by Ein-Tim** [comment] 2022-03-13 17:29
@timokoenig Is this reliably reproducible?

**Comment by timokoenig** [comment] 2022-03-13 17:32
@Ein-Tim it seems like it. I'm currently trying to get a demo certificate to investigate this better

**Comment by timokoenig** [comment] 2022-03-14 00:00
The compression infinite loop that I mentioned earlier should not matter since this is only being used in unit tests. I will investigate more when the team clarified that nothing changed with the certificate issuing service.

**Comment by markusgallmetzer** [comment] 2022-05-23 10:55
Hi,

is this bug fixed?

I am not sure whether my issue  is related (iOS 15.5, Covpass 1.23) to this issue but it seams that at least the symptoms are the same and I do not want to create a new issue.

I am trying to add the certificate of my child after adding my own certificate. Adding the first certificate always succeeds and after that, adding the second certificate freezes the application to the point that I have to terminate and restart the app in order to be able to use it again.

This happens every single time.

Both certificates _can_ be added though. I tested by removing the app and adding the certificate of my child first. Then it freezes adding mine.

Best regards

**Comment by weinzierl-florian** [comment] 2022-07-24 13:45
I’m not sure whether there were some fixes, but as of my recent test (iOS 15.5 CovPass 1.27) adding the second certificate worked fine.

But the problem you described sounds in fact quite similar to mine.

**Comment by markusgallmetzer** [comment] 2022-07-25 08:56
Hi,

thanks for trying it out again. I tried it out as well (iOS 15.5, Compass 1.27 (1)) with a similar result regarding the certificates: the second one fails to be added. Always.

But it does not freeze the application anymore...

**Comment by Ein-Tim** [comment] 2022-07-25 12:17
@Kurt57 or @alexcimander

Could you update us on this issue?

**Comment by markusgallmetzer** [comment] 2022-07-25 14:47
Out of curiosity I looked into the device logs. "CovPassApp" did not freeze but apparently the application crashes.

The Console is full of messages from the "CovPassApp" and needless to say I cannot spot anything obvious.

I must confess I hoped for a stack trace starting with a message similar to "Failed to add certificate" 😀 

I may provide logs...

**Comment by Kurt57** [comment] 2022-07-25 17:03
Hi @markusgallmetzer 

could you provide a video ?

Regards,
Fatih

**Comment by Ein-Tim** [comment] 2022-07-25 17:15
Please do not provide a video with the EU DCC QR code here on GitHub!

@Kurt57 If you want/need a video, I suggest to provide a Mail address where the video can be send to.

**Comment by Kurt57** [comment] 2022-07-26 08:14
@markusgallmetzer you can provide a censored video here if it was not clear 😀

If you prefer a Mail then mailto:support@covpass-app.de and set the hint that should be forwarded to development team.

**Comment by markusgallmetzer** [comment] 2022-07-26 10:30
@Kurt57 Sorry, I cannot do that. I will not send the video without being properly censored  and I am no video editor. I tried to use some iOS apps (e.g. Blur Video https://apps.apple.com/us/app/blur-video/id1555770514) for a while now but without any significant success.

I can provide logs though.

**Comment by Kurt57** [comment] 2022-07-27 06:06
Please send logs. Let's see if there is something useful.

**Comment by Kurt57** [comment] 2023-07-19 09:30
i will close this issue because of missing reply, seems like it is obsolete.

**Closed by Kurt57** 2023-07-19 09:30 UTC
Labels: bug
