### ISSUE TITLE
Cannot check Austrian rules

### ISSUE THREAD

**Issue by timokoenig** [Digitaler-Impfnachweis/covpass-ios#160] opened 2022-03-07 12:55 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- App version: 1.19.0

## Describe the bug

The app states that there are no rules for the given time and country but there are actually 5 active rules for vaccination certificates.

https://timokoenig.github.io/eu-dcc-rules/?ruleset=eu-dcc-rules&country=AT&rule=VR-AT-0000

## Steps to reproduce the issue

1. Open Check Validity
2. Select Austria
3. See that the app cannot check the certificate

<img src="https://user-images.githubusercontent.com/4365095/157038292-1b49f1fb-9036-4fd8-a6d9-92054d8d69e9.PNG" width="300" />

## Expected behaviour

The app should check all five active rules.

**Comment by Ein-Tim** [comment] 2022-03-07 14:26
This is the result when checking with CWA:

<img src="https://user-images.githubusercontent.com/67682506/157052674-c808f2b5-2991-4a88-9b4a-642e629c51b1.png" width="300">

**Comment by timokoenig** [comment] 2022-03-07 14:27
@Ein-Tim you're right. Works fine in CWA

**Comment by timokoenig** [comment] 2022-03-07 14:36
Just noticed that Austria has also two general rules. Therefore CovPass should check 7 rules ( 2 general + 5 vaccination )

**Comment by alexcimander** [comment] 2022-03-08 13:53
Thank you for reporting this bug - we will keep you updated about the cause of the bug and how we solve it.

**Comment by pucherd** [comment] 2022-03-21 17:46
Hi @timokoenig, looks like Austria is the only country which is filling the "region" property with country code "AT" (all other countries are having null).
And the certLogic is doing some additional check for the region:
https://github.com/eu-digital-green-certificates/dgc-certlogic-android/blob/93a32104fb084af22b9c6b50aea9ff245d8bd039/engine/src/main/java/dgca/verifier/app/engine/domain/rules/DefaultGetRulesUseCase.kt#L71

selectedRegion is optional and we are passing null and the ruleRegion is for all countries except Austria also null.
After I locally removed this check the validation for Austria is done with 7 rules.

**Comment by Kurt57** [comment] 2023-07-19 09:29
i going to close this issue because check validity feature is not anymore available in the app

**Closed by Kurt57** 2023-07-19 09:29 UTC
Labels: bug
