### ISSUE TITLE
Incorrect app icon display when closing the app

### ISSUE THREAD

**Issue by beneeeeeee** [Digitaler-Impfnachweis/covpass-ios#29] opened 2021-07-01 15:24 UTC
The animation is displayed incorrectly while closing the app (white border around the app icon).

![IMG_6425](https://user-images.githubusercontent.com/80888846/124149885-4eace980-da91-11eb-9759-cc3bee08f962.jpg)

![IMG_6424](https://user-images.githubusercontent.com/80888846/124149694-21f8d200-da91-11eb-91d6-cb4accdfe894.jpg)

**Comment by timokoenig** [comment] 2021-07-01 15:54
Duplicate of https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/14

**Closed by timokoenig** 2021-07-01 15:54 UTC
