### ISSUE TITLE
CovPass App iOS - unreadable and unfitting UI message for EU print function

### ISSUE THREAD

**Issue by Ron-70** [Digitaler-Impfnachweis/covpass-ios#103] opened 2022-01-19 07:05 UTC
## Technical details

- Device name: iPhone 6
- OS version: iOS 12.5
- App version: CovPass App Version 1.15 and 1.16

## Description

After selecting the function "EU-Ausdruck erstellen" (EU print) the appearing UI message dialog is nearly unreadable and quite unfitting. 

Screenshot (iPhone 6 running iOS 12.5):
![grafik](https://user-images.githubusercontent.com/52568084/150080626-c8c6d741-6169-49b1-ac95-1f309dbcaa88.png)

## Steps to reproduce the issue

Select button "EU-Ausdruck erstellen".

## Expected behaviour

Proper UI message dialog.

**Comment by Ein-Tim** [comment] 2022-01-19 10:29
Can't reproduce on iOS 15.2.1 on an iPhone XR.

<img src="https://user-images.githubusercontent.com/67682506/150112744-9e4e3356-e0dd-4b26-98f7-9fad391ce167.png" width="300">

**Comment by timokoenig** [comment] 2022-03-22 15:01
Did anyone from the team checked it on a iPhone 6 with accessibility option Large Text all the way to the max? I can reproduce similar issues with the iPhone 11 Pro Max, then I would guess this is the exact setting for that image above on a smaller device.

**Comment by Kurt57** [comment] 2022-03-22 15:22
Yes, and cannot reproduce this. (iPhone SE)

**Comment by Ron-70** [comment] 2022-04-26 11:42
>

**Comment by Ron-70** [comment] 2022-04-26 11:43
> @Ron-70 can you even reproduce that? If not may we can close this issue?

I just updated to CovPass App version 1.22.1 and it's still the same issue (iPhone 6 / iOS 12.5).

**Comment by Ron-70** [comment] 2022-04-27 08:15
> Did anyone from the team checked it on a iPhone 6 with accessibility option Large Text all the way to the max? I can reproduce similar issues with the iPhone 11 Pro Max, then I would guess this is the exact setting for that image above on a smaller device.

By the way, the accessibility option "Large Text" is switched off on my iPhone where the wrong behaviour occurs.
![image2](https://user-images.githubusercontent.com/52568084/165473093-770b9120-18b4-43c5-baf5-17f905b59d61.png)

**Comment by Kurt57** [comment] 2022-04-28 00:10
Ok this is default setting and tested with this, even not reproducible.

Do you have some custom settings in Font sizes or something similar ? @Ron-70

**Comment by Ron-70** [comment] 2022-04-28 17:49
> Ok this is default setting and tested with this, even not reproducible.
> 
> Do you have some custom settings in Font sizes or something similar ? @Ron-70

I have no custom font size settings or similar. The problem is for me always reproducable on iPhone 6 running on iOS 12.5. See attached screen recording.

https://user-images.githubusercontent.com/52568084/165815743-643ff7c6-55a4-40d7-bb91-09c73f624895.MOV

**Comment by timokoenig** [comment] 2022-12-09 10:47
Fixed with v1.37.1

**Closed by timokoenig** 2022-12-09 10:47 UTC
Labels: bug
