### ISSUE TITLE
Certificates lost after 'Restore from Backup'

### ISSUE THREAD

**Issue by michael-koeller** [Digitaler-Impfnachweis/covpass-ios#58] opened 2021-10-25 05:57 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 8
- OS version: 15.0.2
- App version: 1.11.1

## Describe the bug

The CovPass App stores its certification data in a way that does not survive a backup/restpre-cylcle.
After 'Restore from Backup' on an iOS device, all certification data ist lost.

## Steps to reproduce the issue

1. Restister certificates in the CovPass app via QR-Code scan.
2. Create a baclup of yout iOS device.
3. Reset the iOS device to factory settings.
4. Execute the 'Restore from Backup' option.
5. After successful installation, open the CovPass app.
6. Open the CovPass app.

## Expected behaviour

Expected: All registered certificates are still present.

## Possible Fix

Take a look at the similar function in the [CoronaWarn app](https://github.com/corona-warn-app/cwa-app-ios), where described procedure does not loose any data.

## Additional context

n.a.

**Comment by jleufgen** [comment] 2021-12-07 14:32
@michael-koeller thanks for your effort! Could you reproduce the bug again? We couldn't.. Maybe the bug no longer exists due to the release updates.

**Comment by Ein-Tim** [comment] 2022-04-18 11:31
@jleufgen If there is no feedback from @michael-koeller, I suggest to close this issue, especially because you said you weren't able to reproduce this issue.

**Comment by Kurt57** [comment] 2022-04-19 06:36
@Ein-Tim thanks for your feedback. I also see like that and close this issue.

**Closed by Kurt57** 2022-04-19 06:36 UTC
Labels: bug
