### ISSUE TITLE
Latest Vaccination Certificate not active even after 14 days 

### ISSUE THREAD

**Issue by Deepanya** [Digitaler-Impfnachweis/covpass-ios#138] opened 2022-02-21 09:51 UTC
## Technical details

- Device name: iPhone
- OS version:14.8.1
- App version: 1.18(1)

## Describe the bug

< I got my third shot of vaccination on 3rd February 2022. But till date the active and valid certificate that the App is showing is the second on. Even after the 14 days 
![272901BA-2782-4B6D-B3F0-D4C49E8F0487](https://user-images.githubusercontent.com/100126375/154930535-b8d91bd9-b921-4e79-8e57-3eb3b12e3cdb.jpeg)
>

**Comment by timokoenig** [comment] 2022-02-21 11:19
Possible reason for the issue is that the certificates need to be ordered first before calling the sortLatest() function, otherwise the sorting of that function is wrong

[sortLatest](https://github.com/Digitaler-Impfnachweis/covpass-ios/blob/8cfce4ca8ccfbdc6d97938a7656e2847b59683d0/Source/CovPassCommon/Sources/CovPassCommon/Utils/CertificateSorter.swift#L89)

**Comment by Ein-Tim** [comment] 2022-02-21 11:24
@Deepanya If you remove the "2 of 1" cert and add it back afterwards, which is the active certificate then?

**Comment by Deepanya** [comment] 2022-02-21 14:44
If i remove 2of1, then 3of1 is activated.. then upon adding 2of1 the 3of1 stay active. so it is ok. 

why is it still not showing that I am 2G+, with booster shot as well?

**Comment by timokoenig** [comment] 2022-02-21 14:46
Seems to be the workaround for now but that should be fixed.

@Deepanya do you mean in CovPass or CovPassCheck?

**Comment by Deepanya** [comment] 2022-02-21 14:48
I meant CovPass.. does it not show that I am 2G+ status? is that functionality not there in CovPass? to Show to it user, that they already qualify for CovPass?

**Comment by timokoenig** [comment] 2022-02-21 14:51
@Deepanya CWA implemented this feature but CovPass did not.

Not sure if this is part of the CovPass backlog

**Comment by Ein-Tim** [comment] 2022-02-21 16:14
CWA will show you 2G+ in the next version.

**Comment by alexcimander** [comment] 2022-02-28 11:08
Hey everyone!

thank you for reporting this bug. We are currently working on a solution for it so that a 3/1 will be prioritized over a 2/1 certificate. 

thank you!

**Closed** 2022-06-15 09:43 UTC
Labels: bug
