### ISSUE TITLE
COV-Pass Check app accepts single Johnson & Johnson shots

### ISSUE THREAD

**Issue by BengtHagemeister** [Digitaler-Impfnachweis/covpass-ios#101] opened 2022-01-17 23:22 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: 
- OS version: Android & iOS
- App version: 1.15

## Describe the bug

Since 15.01.2022 there is a new regulation (Verordnung zur Änderung der COVID-19-Schutzmaßnahmen-Ausnahmenverordnung) that changes the amount of shots needed for Johnson & Johnson Vaccines. 

Here is the publication in "Bundesanzeiger": https://www.bundesanzeiger.de/pub/publication/yW2hBRkcEPpvCQIb8IT/content/yW2hBRkcEPpvCQIb8IT/BAnz%20AT%2014.01.2022%20V1.pdf?inline.

It is specified that the publication of the Paul-Ehrlich-Institut has to be followed (see also https://www.gesetze-im-internet.de/schausnahmv/BJNR612800021.html -> §2 3a).

For Johnson & Johnson it is specified that your only fully vaccinated when you have 2 shots (https://www.pei.de/DE/newsroom/dossier/coronavirus/coronavirus-inhalt.html?nn=169730&cms_pos=3).

At the moment the app still accepts single shots.

## Expected behaviour

The app should decline certificates with only one Johnson & Johnson shot.

## Possible Fix

Add a rule that overwrites the logic in the certificate.

## Additional context

Paul-Ehrlich-Insitut: https://www.pei.de/DE/newsroom/dossier/coronavirus/coronavirus-inhalt.html?nn=169730&cms_pos=3

Bundeanzeiger Publication: https://www.bundesanzeiger.de/pub/publication/yW2hBRkcEPpvCQIb8IT/content/yW2hBRkcEPpvCQIb8IT/BAnz%20AT%2014.01.2022%20V1.pdf?inline.

Gesetzte im Internet: https://www.gesetze-im-internet.de/schausnahmv/BJNR612800021.html

**Comment by timokoenig** [comment] 2022-01-18 01:19
Duplicate of https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/97

**Comment by Ein-Tim** [comment] 2022-01-18 05:40
@BengtHagemeister 

Can you add your comment to #97, please?

**Closed** 2022-01-18 09:33 UTC
Labels: bug
