### ISSUE TITLE
Vaccine Name not displayed

### ISSUE THREAD

**Issue by Hoppes94** [Digitaler-Impfnachweis/covpass-ios#139] opened 2022-02-21 10:39 UTC
We have a problem with the app. Some devices with the release version 1.18 do not display the vaccine name and manufacturer.
Unfortunately the original value of vp and ma are shown.

![image](https://user-images.githubusercontent.com/56299069/154937956-3cc75ce2-3342-4ae9-83b7-ec29d37fa51c.png)
[https://github.com/Digitaler-Impfnachweis/certification-apis/blob/master/Implementation.md](url)

We are currently busy with the facility-related compulsory vaccination and my colleagues record the date of the vaccination and the used vaccine. Since friday they contacted me with this issue.

I don´t know if this issue happens only on specific devices.

**Comment by timokoenig** [comment] 2022-02-21 11:13
Issue is a duplicate of https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/109

**Closed** 2022-02-21 11:13 UTC
Labels: bug
