### ISSUE TITLE
CovPass App uses not the latest certificate for the "Gültigkeit prüfen" feature

### ISSUE THREAD

**Issue by JonasDeichelmann** [Digitaler-Impfnachweis/covpass-ios#50] opened 2021-09-17 10:35 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone von Jonas Deichelmann
- OS version: iOS 14.7.1
- App version: 1.8

## Describe the bug

In the CovPass App I've scanned my booster certificate 3/3. I've also my two other certificates scanned in the App. When I'm using the "Gültigkeit prüfen" feature the App uses the 2/2 certificate and not the newer 3/3 certificate.

## Steps to reproduce the issue
![IMG_03ECC5A2D421-1](https://user-images.githubusercontent.com/20640553/133768796-fad8e816-b396-4cb6-9044-55104e33e027.jpeg)
![133754426-8a7977f9-bae5-4be7-b214-8858349fe1b7](https://user-images.githubusercontent.com/20640553/133768893-120d5fa8-93eb-4ad0-bd5c-a5ff744403c4.jpeg)
![133753418-af96dbaf-43ce-40ce-a8be-63927336d319](https://user-images.githubusercontent.com/20640553/133768992-2016d7ab-ce7e-4d67-b665-884a9adf8430.jpeg)

## Expected behaviour

The Expected behaviour would be, that the App uses the latest certificate for the "Gültigkeit prüfen" feature.

## Possible Fix

Check if there is a latest certificate and then use this certificate for checking the validity.

## Additional context

Please see also the referring Ticket in the CWA Repo: https://github.com/corona-warn-app/cwa-documentation/issues/709

**Comment by jleufgen** [comment] 2021-09-20 10:48
The rule update is in progress. The CovPass will interpret the rule in the same way like CWA and return a warning message. The CovPassCheck will also return an error for this type of certificate.

**Comment by Ein-Tim** [comment] 2021-09-20 11:33
@jleufgen 

The problem isn't the rule update but the fact that CovPass does not checks the 3/3 certificate but the 2/2 certificate.

**Comment by timokoenig** [comment] 2021-09-20 13:46
No, CovPass checks all certificates but because 3/3 is currently still invalid (if within 14 days) we show the next valid certificate with that you can enter the selected country. Therefore you see the 2/2 certificate instead of the 3/3. After the rules have been updated the correct certificate will be shown, in this case 3/3.

**Comment by Ein-Tim** [comment] 2021-09-20 13:52
@timokoenig Okay, thanks for the explanation.

**Comment by jleufgen** [comment] 2021-09-27 10:12
@timokoenig can we close this ticket?

**Comment by Ein-Tim** [comment] 2021-09-27 11:30
@jleufgen 

Yes, IHMO, @timokoenig's explanation is sufficient. Thanks for asking! 

(I hope @JonasDeichelmann, who opened this issue, does agree with me here)

**Closed** 2021-09-27 11:36 UTC
Labels: bug

**Comment by Kurt57** [comment] 2021-11-03 22:25
@JonasDeichelmann is your problem solved ?

**Comment by JonasDeichelmann** [comment] 2021-11-03 22:29
@Kurt57 
Yes, I just checked it out. Thank you for working on this.
