### ISSUE TITLE
Booster recommendation although already boostered

### ISSUE THREAD

**Issue by Kamik423** [Digitaler-Impfnachweis/covpass-ios#81] opened 2021-12-09 12:49 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11
- OS version: 15.2 RC
- App version: 1.13 (5)

## Describe the bug

The app recommends I get boostered although I did this week and scanned the certificate for it.

## Steps to reproduce the issue

This might be due to the fact that the booster is not yet 14 days old. But it gets shown with a green tick mark and the app should then at least know that it will be valid soon.

![DB22C82F-8F55-4A75-B30E-932C20367344](https://user-images.githubusercontent.com/16278233/145399338-154a45ef-27af-4f32-9834-a5e4c842564a.jpeg)

**Comment by Ein-Tim** [comment] 2021-12-09 12:56
When did you add the booster?

**Comment by Kamik423** [comment] 2021-12-09 12:59
The day I got vaccinated since they immediately gave me the certificate and I found scanning it now better than scanning it in two weeks and not finding the slip of paper anymore.

**Comment by Ein-Tim** [comment] 2021-12-09 13:01
@Kamik423 

And since then the booster recommendation is shown?

In General I can only say that the 3/3 certificate is wrong here, as the booster shot was your second and not your third dose, so the certificate should be 2/2.

**Comment by Kamik423** [comment] 2021-12-09 13:04
I had the warning already before that since it is recommended to get bolstered with only one J&J shot. The people at the vaccination center had to consult first as they don't seem to get a lot of J&J people but they later explained to me that this is correct since the booster shot has to be marked as number 3 and not number 2.

**Comment by Ein-Tim** [comment] 2021-12-09 13:18
This is not true see also the second part of my comment here: https://github.com/Digitaler-Impfnachweis/covpass-android/issues/94#issuecomment-972823485

**Comment by Kamik423** [comment] 2021-12-09 13:30
Is there a way for me or other end-users to fix this? I am most certainly not the only one having this issue and many of those people are likely not tech-savvy. If this cannot automatically be patched in the app can you add put a warning icon that informs you about the likely mixup and tells you how to fix it.

Do I have to go to a pharmacy to get the original certificate-code changed?

**Comment by Kamik423** [comment] 2021-12-09 13:32
Although it does not really make sense since you **can** show basic immunization with the J&J vaccine from the 1/1 dosage, right? So it should not actually be an issue.

**Comment by Kamik423** [comment] 2021-12-09 13:44
Additionally the app should then not show the `Complete since <day of booster>` in its main screen.

BTW: I just added these same codes to the CovPass app on my iPad and here I don't get the popup urging me to get boostered.

**Comment by timokoenig** [comment] 2021-12-09 14:04
@Kamik423 I think the certificates are only checked once a day so maybe tomorrow you will get a notification there as well

**Comment by timokoenig** [comment] 2021-12-09 14:07
@Ein-Tim I checked the rule and it should clearly only be shown to J&J 1/1 certificates. This might be only a UI issue where the rule is added to the wrong certificate and does not consider the added booster certificate. @alexcimander can you add this to your list of bugs? Thanks!

**Comment by Ein-Tim** [comment] 2021-12-09 14:07
@timokoenig Thanks for checking!

**Comment by timokoenig** [comment] 2021-12-09 14:08
Or maybe the existing message does not get deleted when the booster is added

**Comment by Ein-Tim** [comment] 2021-12-09 14:09
@timokoenig 

It should latest be deleted when a new check is done, or not?

**Comment by timokoenig** [comment] 2021-12-09 14:11
@Ein-Tim yes I would say so. That would be 24 hours or less after the booster has been added

**Comment by Ein-Tim** [comment] 2021-12-09 14:11
> Additionally the app should then not show the Complete since <day of booster> in its main screen.
 
 Reported in: https://github.com/Digitaler-Impfnachweis/covpass-android/issues/94

> Although it does not really make sense since you can show basic immunization with the J&J vaccine from the 1/1 dosage, right? 

Yes

> Is there a way for me or other end-users to fix this? I am most certainly not the only one having this issue and many of those people are likely not tech-savvy. If this cannot automatically be patched in the app can you add put a warning icon that informs you about the likely mixup and tells you how to fix it.

The data of the certificate can't be changed as it is verified with a signature, if the content of the certificate changes the signature breaks.  
A warning icon could be shown but what about user who only add a 3/3 to their app? The app has no way to tell if this is correct or not.

> Do I have to go to a pharmacy to get the original certificate-code changed?

Yes.

**Comment by Kamik423** [comment] 2021-12-09 15:43
But is there a reason to get the certificate re-issued? Would that change anything about the apps behavior in any situation?

**Comment by Ein-Tim** [comment] 2021-12-09 15:43
@Kamik423 Not sure, sorry (-:

**Comment by timokoenig** [comment] 2021-12-09 15:49
@Kamik423 you could change it to a 2/2 in the pharmacy but in my opinion you don't need to. All checks and rules should still work with your certificate

**Comment by Ein-Tim** [comment] 2021-12-12 15:07
Do you still see this issue @Kamik423?

**Comment by Kamik423** [comment] 2021-12-12 19:05
Yes, it is still occurring, I tho k deleting and setting it up again would fix it but I might keep it so I can update you on if it still exists?

Setting it up from scratch on my iPad did not have the message.

Maybe it is an issue with Unicode normalization in my last name that the certificates don’t get correctly linked?

**Comment by Ein-Tim** [comment] 2021-12-12 19:14
@Kamik423 

If the certificates are assigned to one person the app should know it's one person.

**Comment by timokoenig** [comment] 2021-12-12 19:41
@Kamik423 I think the best is to keep it so we can check in the future if a bugfix removes the message.

I just had a quick look. The booster rule does not get deleted correctly.

https://github.com/Digitaler-Impfnachweis/covpass-ios/blob/61ffab4fbde9ad89916229a7813348504578f916/Source/CovPassCommon/Sources/CovPassCommon/CertLogic/BoosterLogic.swift#L104

**Example:**
User has two certificates, and has a valid booster rule. This rule gets saved for the second certificate of that user. Now the user gets boostered and scans the third certificate. The app tries to delete the booster rule for the most recent certificate, in this case the third and not the second. The booster rule for the second certificate stays alive and the message never disappears.

**Solution:**
Delete booster rules based on the user and not a specific certificate of that user

**Comment by alexcimander** [comment] 2021-12-15 13:20
thank you @timokoenig for the investigation and thank you everyone for the discussion! We opened up a ticket for this bug 🚧

**Comment by Ein-Tim** [comment] 2021-12-19 09:38
I can **confirm** this issue.
I added a 3/3 certificate on top of a 2/2 certificate 3 days ago, the booster recommendation is still shown.

**Comment by Kamik423** [comment] 2022-01-15 13:56
The latest update did not fix the issue.

**Comment by mirabilos** [comment] 2022-01-22 07:06
Right, I got 1/2 2/2 and 3/3 one day after I got the update that first displayed these warnings IIRC, and they don’t go away.

**Comment by Ein-Tim** [comment] 2022-01-27 21:28
I can still reproduce this issue. Is there any fix in sight @alexcimander?

**Comment by Kamik423** [comment] 2022-02-02 12:25
Still occurs in 1.17

**Comment by Kamik423** [comment] 2022-02-18 00:35
The latest version fixes this issue for me. Same for you @Ein-Tim?

**Comment by Ein-Tim** [comment] 2022-02-18 05:34
@Kamik423 Yes 👍

**Closed** 2022-02-18 10:25 UTC
Labels: bug
